# Create block pools as defined on variables

- name: ROOK - Create Block Storage pools
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'storages/ceph_block_pool.yaml.j2') | from_yaml }}"
  register: result
  until: result.failed == 0 or (result.rc is defined and result.rc !=0) or (result.status is defined and result.status != 200)
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ ceph_block_storage_pools }}"
  tags: storage_creation
