# Create storage classes as defined on variables

- name: ROOK - Create K8s Storage Classes
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'storages/storageclass.yaml.j2') | from_yaml }}"
    force: "{{ item.force | default(omit) }}"
  register: ret
  until: |
    not ret.get('failed', false)
    or ret.get('status', 200) != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ rook_storage_classes }}"
  loop_control:
    label: "{{ item | to_nice_yaml }}"
  tags:
  - storage_creation
  - class_creation
